import {describe, expect, it} from 'vitest';

import {
  pressSpace,
  releaseSpace,
  type SpaceAction,
  type SpaceOutcome,
  type SpacePress,
} from '@/lib/space-key';

/**
 * Plays a sequence of Space events against the state machine.
 *
 * The recorder's status is derived from the actions themselves, exactly as it is
 * in the browser, so a test cannot accidentally hand the machine a status the
 * real recorder would never be in.
 *
 * @param events `down`, `up`, or `hold` for a repeat generated by a held key.
 * @returns Every action taken, in order, with nothing dropped.
 */
function play(events: ReadonlyArray<'down' | 'up' | 'hold'>): SpaceAction[] {
  let press: SpacePress = 'idle';
  let isRecording = false;
  const actions: SpaceAction[] = [];

  for (const event of events) {
    const outcome: SpaceOutcome =
      event === 'up' ? releaseSpace(press) : pressSpace(press, isRecording, event === 'hold');
    press = outcome.press;

    if (outcome.action) {
      isRecording = outcome.action === 'start';
      actions.push(outcome.action);
    }
  }

  return actions;
}

describe('recording with the spacebar', () => {
  it('starts on the release, so the press is not in the take', () => {
    expect(play(['down'])).toEqual([]);
    expect(play(['down', 'up'])).toEqual(['start']);
  });

  it('stops on the next press and stays stopped', () => {
    // The reported bug. Reading the recorder's status on the release cannot tell
    // "this key just stopped a take" from "nothing is being recorded", so the
    // release that ended a take immediately started another one.
    expect(play(['down', 'up', 'down', 'up'])).toEqual(['start', 'stop']);
  });

  it('records once per pair of presses, however many pairs', () => {
    expect(play(['down', 'up', 'down', 'up', 'down', 'up', 'down', 'up'])).toEqual([
      'start',
      'stop',
      'start',
      'stop',
    ]);
  });

  it('records once when Space is held down', () => {
    // A held key repeats `keydown`. Without a guard this stops and restarts for
    // as long as the key is down.
    expect(play(['down', 'hold', 'hold', 'hold', 'up'])).toEqual(['start']);
  });

  it('keeps recording while Space is held down during a take', () => {
    expect(play(['down', 'up', 'down', 'hold', 'hold', 'up'])).toEqual(['start', 'stop']);
  });

  it('ignores a release with no press behind it', () => {
    // The tab took focus mid-keystroke, or a dialog owned the press. Neither is
    // an instruction to start recording.
    expect(play(['up'])).toEqual([]);
    expect(play(['up', 'up'])).toEqual([]);
  });
});

describe('pressSpace', () => {
  it('arms a press that finds nothing being recorded', () => {
    expect(pressSpace('idle', false, false)).toEqual({press: 'armed', action: null});
  });

  it('consumes a press that stops a take', () => {
    expect(pressSpace('idle', true, false)).toEqual({press: 'consumed', action: 'stop'});
  });

  it('leaves the press untouched when the key is repeating', () => {
    expect(pressSpace('armed', false, true)).toEqual({press: 'armed', action: null});
    expect(pressSpace('consumed', true, true)).toEqual({press: 'consumed', action: null});
  });
});

describe('releaseSpace', () => {
  it('starts a take for an armed press', () => {
    expect(releaseSpace('armed')).toEqual({press: 'idle', action: 'start'});
  });

  it('does nothing for a press that already stopped one', () => {
    expect(releaseSpace('consumed')).toEqual({press: 'idle', action: null});
  });

  it('always returns to idle, so a lost press cannot strand the machine', () => {
    expect(releaseSpace('idle').press).toBe('idle');
    expect(releaseSpace('armed').press).toBe('idle');
    expect(releaseSpace('consumed').press).toBe('idle');
  });
});
